SUMMARIZATION_MODEL = "google/flan-t5-small"

CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

SPACY_MODEL = "en_core_web_sm"

MAX_SUMMARY_LENGTH = 120
MIN_SUMMARY_LENGTH = 30

DIRECT_THRESHOLD = 0.70
PARTIAL_THRESHOLD = 0.40